AllCops:
  TargetRubyVersion: 2.4
  Include:
    - '**/Rakefile'
    - '**/config.ru'
    - '**/Gemfile'
  Exclude:
    - 'bin/*'

# Accept single-line methods with no body
SingleLineMethods:
  AllowIfMethodIsEmpty: true

# Prefer double_quotes strings unless your string literal contains escape chars
StringLiterals:
  EnforcedStyle: double_quotes

# Prefer raise over fail for exceptions
Style/SignalException:
  EnforcedStyle: only_raise

# Prefer parentheses for almost all percent literals
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '()'
    '%I': '()'
    '%w': '()'
    '%W': '()'

# Non ASCII chars are permitted in comments
Style/AsciiComments:
  Enabled: false

# Test methods, blocks, and class with unlimited length
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'spec/**/*.rb'
    - 'test/**/*.rb'
    - 'lib/tasks/*.rake'

Metrics/MethodLength:
  Enabled: true
  Exclude:
    - 'test/**/*.rb'

Metrics/ClassLength:
  Enabled: true
  Exclude:
    - 'test/**/*.rb'

Metrics/LineLength:
  Exclude:
    - 'test/**/*.rb'
    - '*.gemspec'

Metrics/AbcSize:
  Exclude:
    - 'test/**/*.rb'

